version: '3.8'

services:
  node:
    build: .
    env_file: .env
    ports:
      - "${NODE_LOCAL_PORT}:$NODE_DOCKER_PORT"
    stdin_open: true
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    command: yarn start
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "${MONGODB_LOCAL_PORT}:$MONGODB_DOCKER_PORT"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: